[package]
name = "minimp4-sys"
version = "0.1.1"
authors = ["DarkSky"]
edition = "2021"
description = "A minimp4 ffi binding"
include = ["src/**/*", "build.rs", "minimp4.*", "Cargo.toml", "README.md", "LICENSE"]
license = "MPL 2.0"
homepage = "https://github.com/darkskygit/minimp4.rs"
readme = "README.md"
keywords = ["minimp4", "ffi", "bindings"]
repository = "https://github.com/darkskygit/minimp4.rs"
categories = ["external-ffi-bindings"]

[build-dependencies]
bindgen = "0.66.1"
cc = { version = "1.0.81", features = ["parallel"] }
